name: cubixd
description: An animated 3d cube widget and static 3d cube widget, support selection.
version: 0.1.1
repository: https://github.com/ElRojo7u7/cubixd
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  vector_math: ^2.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
